### ISSUE TITLE
Diseñar maquetado de la casa

### ISSUE THREAD

**Issue by Leytonale** [ISPC-TST-CONTROL-Y-SERVICIOS/proyecto-1-grupo-3#8]
Definir la distribución de zonas en la casa y crear un maquetado para el sistema de control de temperatura, identificando las distintas áreas y su ubicación. Además, considerar los requisitos de temperatura para cada zona.

**Comment by Leytonale** [comment]
**Herramientas que se pueden utilizar para diseñar el plano:**

- https://cedreo.com/es/ 
   *Plataforma paga con tiempo de prueba gratuito 
   *Requiere crear una cuenta o usar cuenta de google]
   *Especifica para diseño de planos en 2d y 3d
- https://www.lucidchart.com/pages/ 
  *Plataforma de diagramado gratis
  *Requiere cuenta ya sea de google o creada.
  *No es especifica para crear planos en 2d pero tambien sirve para diagramarlo/maquetarlo-
  
**Recursos**
_Sugiero inspirarse de otros planos se pueden guiar de estas paginas u otras que encuentren_

- https://documentos.arq.com.mx/Planos_y_Modelos/Planos_de_Casas/index.html
- https://www.dwgautocad.com/planos-casas.html
- https://planoscadgratis.com/category/planos-de-casas-gratis-en-dwg/

**Comment by fvexe82** [comment]
Subido plano en carpeta simulación
